### ISSUE TITLE
".みんな" domain is determined to be invalid

### ISSUE THREAD

**Issue by Qs-F** [miguelmota/is-valid-domain#21]
Some new gTLDs use Japanese or Chinese.
".みんな" domain is one of the examples (you can get more information at http://xn--p8j9a0d9c9a.xn--q9jyb4c )

However, it seems with this library these are determined to be invalid.  
(I checked with this site https://lab.miguelmota.com/is-valid-domain/example/ )

**Comment by miguelmota** [comment]
@Qs-F Added a new option `allowUnicode` to allow unicode/utf8 characters. When this option is `true`, it will convert unicode characters to ascii using `punycode` library.

```js
console.log(isValidDomain('はじめよう.みんな')) // false
console.log(isValidDomain('はじめよう.みんな', {allowUnicode: true}) // true
```
![DeepinScreenshot_select-area_20210408003519](https://user-images.githubusercontent.com/168240/113986742-6d894000-9802-11eb-81dc-723de8183ba7.png)

I don't want to make this default behavior in order to keep backward compatibility since this library is used in a lot of packages.

Let me know if you have any suggestions.

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/is-valid-domain/commit/5574f8ebfa10db51cb9c1879446bfd60d4e675d2

**Comment by Qs-F** [comment]
Thank you for quick response and fix!

**Comment by chenyong** [comment]
well, https://www.npmjs.com/package/@types/is-valid-domain not updated

**Comment by miguelmota** [comment]
@chenyong types have been added now. See [types/index.d.ts](https://github.com/miguelmota/is-valid-domain/blob/master/types/index.d.ts)

**Comment by chenyong** [comment]
Cool!
